### ISSUE TITLE
Switch to MIT license

### ISSUE THREAD

**Issue by tony** [tmux-python/tmuxp#264]
I'd like to switch the license to something even more permissive than BSD 3-clause (MIT).

Sorry for causing the ping, but wanted to get it out of the way.

If you're ok with it, please reply with a note that you agree for your code contribution(s) to tmuxp to be released under the MIT license.

- [x] @ikirudennis 
- [x] @ThiefMaster 
- [x] @sebastianst 
- [x] @kmactavish
- [x] @thomasballinger
- [x] @madprog
- [x] @tasdomas
- [x] @myw
- [x] @fpietka
- [ ] @roxit
- [x] @jorise
- [x] @apieum (by thumbs up)
- [x] @marbu
- [x] @rafi
- [x] @mexicarne
- [x] @stemid (by thumbs up)
- [x] @abeyer
- [x] @ohardy
- [x] @gtback
- [x] @techtonik 
- [x] @raine
- [x] @yegortimoshenko
- [ ] @cryptojuice
- [x] @yvaucher
- [x] @estin
- [x] @achals
- [x] @sehe
- [x] @Omeryl 
- [x] @joelwallis
- [x] @Ilyes512

**Comment by yegortimoshenko** [comment]
Sure.

**Comment by yegortimoshenko** [comment]
BTW, your [LICENSE](https://github.com/tony/tmuxp/blob/master/LICENSE) says to check AUTHORS file for list of contributors, but there is no such file in the repo. Probably makes sense to remove that note.

**Comment by tony** [comment]
When the new license takes effect we'll have the AUTHORS thing out, we'll link to https://github.com/tony/tmuxp/graphs/contributors

**Comment by Ilyes512** [comment]
Good action! I agree.

**Comment by ikirudennis** [comment]
I have no problem with this. Thanks for keeping us all in the loop.

**Comment by techtonik** [comment]
I am fine with it.

**Comment by achals** [comment]
I'm fine with this as well.

**Comment by rafi** [comment]
I agree, thanks!

**Comment by ThiefMaster** [comment]
fine for me

**Comment by mexicarne** [comment]
Ok for me.

**Comment by fpietka** [comment]
Ok for me too

**Comment by abeyer** [comment]
Ok with me

**Comment by tek** [comment]
:+1:

**Comment by marbu** [comment]
I'm ok with it.

**Comment by joelwallis** [comment]
I agree 😄

Joel Wallis Jucá
joelwallis.com

**Comment by sebastianst** [comment]
OK for me.

**Comment by ohardy** [comment]
Ok for me.

**Comment by madprog** [comment]
Ok for me too :)

**Comment by estin** [comment]
I agree.

**Comment by JorisE** [comment]
Ok by me.

**Comment by yvaucher** [comment]
Same here, I agree.

**Comment by gtback** [comment]
fine with me

**Comment by tasdomas** [comment]
Fine with me.

Domas

**Comment by myw** [comment]
I'm OK with this!

**Comment by thomasballinger** [comment]
This is fine with me!

**Comment by tony** [comment]
We're almost there.  @kmactavish @roxit @raine @cryptojuice @sehe @omeryl, do you agree to licensing your contributions under [MIT license](https://opensource.org/licenses/MIT)? If so, reply here that it's Ok!

**Comment by kmactavish** [comment]
Good with me.

**Comment by raine** [comment]
OK!

**Comment by sehe** [comment]
Fine!

**Comment by tony** [comment]
@roxit, @cyptojuice, @omeryl, can you take a look at this issue?

**Comment by tony** [comment]
@roxit, @cryptojuice, @omeryl, can you take a look at this issue?

**Comment by Omeryl** [comment]
@tony I don’t believe I have any code in the repository. The only thing I recall writing is a typo fix to the README. Therefore, do whatever you need.

**Comment by tony** [comment]
thank you @Omeryl !

**Comment by kmactavish** [comment]
@roxit @cryptojuice?

**Comment by tony** [comment]
@cryptojuice @roxit : You okay with relicensing your contributions to MIT?

**Comment by tony** [comment]
Here is @roxit  and @cryptojuice's commits:

@roxit: acd882cf182b9ec98b9f592a6b89c7101eeba4a6 (doc update), 992a50c71187f676249e8eae9f549a19dc37d91d (loading detached)

@cryptojuice acd882cf182b9ec98b9f592a6b89c7101eeba4a6 (typo)

Last call 😆 It's been a couple of months and I want to release MIT. If you're willing to license your commits MIT, please respond here.

If there's no response, this license change can't wait forever, I may revert them and/or rewrite them licensed under MIT.

**Comment by tony** [comment]
One of the code changes from @roxit, @cryptojuice's weren't revertable (findable) from master, so it looks like we're good to do the switch!

#363 merged. Updating LICENSE now.

**Comment by tony** [comment]
1.4.0 is released.

We're MIT. :tada:

**Comment by kageurufu** [comment]
Woot!

**Comment by Ilyes512** [comment]
Nice! (but it took 10 months...wow. I wonder if asking permission was really necessary, besides being a nice thing to do)
