### ISSUE TITLE
Looking for help (support, QA, maintainers)

### ISSUE THREAD

**Issue by tony** [tmux-python/tmuxp#290]
We have a lot of users between here and libtmux. We need to build a team.

Willing to pitch some personal time in to help make tmuxp better?

You're welcome to participate now! We're a well-documented, CI-backed open source project. You can start now by answering [issues](https://github.com/tmux-python/tmuxp/issues) and QA'ing / code reviewing [pull requests](https://github.com/tmux-python/tmuxp/pulls).

If you fit any of these characteristics, you're encouraged to reply here to become a helper / maintainer!

- love open source
- tmuxp user
- Python experience
- tmux experience
- can wrap their brain around the codebase (code quality between tmuxp and libtmux is good)
- Like of or interest in learning [pytest](https://docs.pytest.org/en/latest/)
- Like of or interest in documents (we use [sphinx](http://www.sphinx-doc.org/en/stable/))
- time they can devote to answering/closing issues
- QA'ing pull requests
- Assuring contributions maintain code standards ([flake8](http://flake8.pycqa.org/en/latest/), [vulture](https://github.com/jendrikseipp/vulture))
- Making sure tmuxp and libtmux stay true to what they're philosophically supposed to do, while allowing new features to come in.

Edit: mail me at tony at git dash pull dot com

**Comment by askedrelic** [comment]
I'm spending sometime today looking to fix #184 so maybe I can contribute. I use tmux/tmuxp daily and would like to do what I can do help things be active!

**Comment by tony** [comment]
Another call, need maintainers. 👍

**Comment by tony** [comment]
@askedrelic Are you still available/willing to help out around the project?

**Comment by askedrelic** [comment]
Hi @tony unfortunately I don't know how much time I can commit. I've been watching the tmuxp and libtmux projects the last few months, to get a better sense of things. I'll keep doing so and try to be more active on things.

Sidenote - the pyup and auto ticket mgmt bots are really nice for helping maintain the project!

**Comment by ritiek** [comment]
It probably won't make sense for me to be a maintainer since I am lack on time as well but I'll see around if I can help a bit whenever I get time and the mood. :D

**Comment by suprematis** [comment]
I can volunteer for performing QA.  Feel free to DM me.

**Comment by gunzapper** [comment]
I would help you. I could take a look at issues and also to the QA of merge request. Currently I use tmuxinator... but I am going to start to use tmuxp.

**Comment by sloria** [comment]
@tony You might consider putting this project under the Jazzband org: https://jazzband.co/ .

**Comment by aRkedos** [comment]
@tony I was trying to get my feet wet and implemented #589, `flake8` checks out with no errors, but I can't finish `make test` see #620 :/

**Comment by tony** [comment]
@aRkedos thank you for the error report as well. Tests will run in CI but not sure you'd want to wait for that :)
