### ISSUE TITLE
[Feature] tmuxp ls - show user's directory yml/json workspace files

### ISSUE THREAD

**Issue by rafi** [tmux-python/tmuxp#330]
It would be awesome if tmuxp had an `ls` command (tmux has one) that will list the user directory's yml/json files.

Also, `ln` for a quick way of symlinking project's `.tmuxp.yml` files into the user directory,

For example, _list_, _link_, and _load_ stored workspaces:

```sh
$ tmuxp ls
acme.yml
foo-api.yml

$ cd bar/admin
$ tmuxp ln -s . bar-admin
$ tmuxp ls
acme.yml
foo-api.yml
bar-admin.yml

$ tmuxp load -y foo-api
```

**Comment by pythops** [comment]
I had a need for that option too so I've just opened a PR https://github.com/tmux-python/tmuxp/pull/599 for it.

**Comment by pythops** [comment]
new PR https://github.com/tmux-python/tmuxp/pull/616

**Comment by joseph-flinn** [comment]
the `tmuxp ls` command has been added. 

@rafi Thanks for your ideas! If you are still interested in a `tmuxp ln` command, could you open a new issue (trying to do some house keeping of the older possibly stale issues)
