### ISSUE TITLE
zsh tmuxp command not found

### ISSUE THREAD

**Issue by tienduccao** [tmux-python/tmuxp#331]
Hi, I couldn't install tmuxp command using python2.7 ``pip install --user tmuxp`` (Mac OSX, zsh).
But it was successfully installed using ``pip3 install --user tmuxp``

**Comment by tony** [comment]
Can you ``echo $PATH`` and let me know what it says?

It may be that python bin files from python 3 are in your ``PATH`` environment variable, but python 2 isn't.

**Comment by tony** [comment]
Another point of reference, when I install pip (on macOS, Linux, BSD), I use ``https://bootstrap.pypa.io/get-pip.py`` and run that.

**Comment by tienduccao** [comment]
Here is my $PATH ``/Users/tienduccao/sdks/spark-1.6.3-bin-hadoop2.6/bin:/Users/tienduccao/sdks/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Users/tienduccao/.nexustools
```

**Comment by tienduccao** [comment]
When I tried to use `get-pip.py` script, I got this message `Requirement already up-to-date: pip in ./sdks/anaconda2/lib/python2.7/site-packages`

**Comment by soulofmischief** [comment]
@tienduccao do you see `tmuxp` in `~/.local/bin`? This is the default path for `pip --user` installation path on Linux, I'm not sure about OSX. If it is indeed there, you need to add that location to your `$PATH`. There are lots of guides on how to do this.

**Comment by dvzrv** [comment]
@tienduccao I recommend to not even start dealing with the outdated (bundled) python2 on macOS and install it yourself on top. There are some neat integrations, such as [pyenv](https://github.com/pyenv/pyenv), that you can use to have (multiple) native python2s and python3s specifically for your user!

Another way you can have a more up-to-date python2/3 is to use the `python@2` and `python` (that's 3) packages using [brew](https://brew.sh).

Either way you will have to modify your `PATH` to be able to use the newer version (and its components).

**Comment by tienduccao** [comment]
Thanks all your for help.

**Comment by jcabasc** [comment]
@tienduccao what did work for you?

Thanks.

**Comment by nomasprime** [comment]
If using a version manager, eg, asdf, try reshim.
