### ISSUE TITLE
Add after_script upon exiting tmux

### ISSUE THREAD

**Issue by soulofmischief** [tmux-python/tmuxp#334]
Is it possible to watch for and act on an exit script for tmux?

I poked around the repo for before_script's implementation but couldn't find it. Is this a libtmux issue?

I'm willing to contribute to development of this feature if it wouldn't be much work.

**Comment by beaugunderson** [comment]
I started investigating tmuxp because this feature exists but is currently broken in tmuxinator and I was hoping to switch. :)

**Comment by joseph-flinn** [comment]
@soulofmischief @beaugunderson Thanks for using tmuxp! Unfortunately I didn't see this issue before starting a comment thread on Issue https://github.com/tmux-python/tmuxp/issues/516. I'm going to mark this one as duplicate and close it (even though the other one is the duplicate) and continue any discussion on that one. In light of the new plugin system in version 1.7.0, I hope to start on this task next. Thanks for your contribution!
