### ISSUE TITLE
Create a command to output debug info

### ISSUE THREAD

**Issue by tony** [tmux-python/tmuxp#352]
Create a command to output system information to be used. This should improve quality of issues/bug reports.

Should output:

- Python version
- system PATH
- tmux version
- tmuxp version
- tmux path
- tmuxp path,
- libtmux version 
- shell
- output of ``tmux list-sessions``, ``tmux list-windows``, ``tmux list-panes``
- output of ``tmux show-options -g``, ``tmux show-window-options -g``

For use with https://github.com/tony/tmuxp/issues/351

**Comment by joseph-flinn** [comment]
released in v1.6.2
