### ISSUE TITLE
release to include libtmux 0.7.8

### ISSUE THREAD

**Issue by dvzrv** [tmux-python/tmuxp#360]
hey there,

i moved tmuxp to Arch Linux' community repository. however, I oversaw, that 1.3.5 depends on libtmux 0.7.7.
Is it possible for you to release a new version that is working with 0.7.8?
I'd be happy to ship it right away, otherwise I would have to downgrade the libtmux package and that's an ugly business.

many thanks for this awesome software btw!

**Comment by tony** [comment]
@dvzrv I think I'm going to ship a release tomorrow.

I'm going to be moving tmuxp to an org along with that.

**Comment by tony** [comment]
Also, I may bump up libtmux version again to update to the new @tmux-python org.

Thank you for your kind words.

If you have time / python skills, or know any friends / audiences that may be interested: tmux-python is seeking maintainers to help pitch in. I'm democratizing things a bit around here and we really need some good minds passionate about tmux to help us. Maybe it's you. Maybe it's someone else you know. Maybe now, maybe later. Anything is possible. Here is the link to sign up: https://github.com/tmux-python/tmuxp/issues/290

**Comment by dvzrv** [comment]
@tony that sounds great! Would fix my problem in no time ;-)

I read about #290 a while back, but I currently have not enough time on my hands, as I do a lot of packaging for Arch, that requires me to better the pro-audio sector :-)

In any case, it sounds like an interesting opportunity to get into python again a little more. I'll have a look into it!

**Comment by dvzrv** [comment]
@tony can you do a release, please?

**Comment by tony** [comment]
Today. Yep.

It's okay with libtmux gets updated, and tmuxp gets updated, in sync?

**Comment by dvzrv** [comment]
Yes, as long as both stay in sync (version requirement wise), it'll always be fine for me to update the packages
-- 
https://sleepmap.de

**Comment by tony** [comment]
1.4.0 is released.

libtmux 0.8.0 (https://github.com/tmux-python/tmuxp/blob/v1.4.0/requirements/base.txt)

**Comment by dvzrv** [comment]
@tony thanks a lot!
I had an issue with one of the tests during build however, so I had to disable them for now. Will open a new bug report for it!
