### ISSUE TITLE
Is it possible to add commands without executing?

### ISSUE THREAD

**Issue by Ilyes512** [tmux-python/tmuxp#366]
So I got lots of docker projects and what  I usually do is have a split screen with on the left `docker-compose up` and on the right just the root of the project. 

In my case I don't want to always start al projects. So I was wondering if it was possible to fill in `docker-compose up` in the pane without actually "submitting"/executing. So the only thing I have to do is switch to the pane and press the return button.

**Comment by rfoliva** [comment]
Hi @Ilyes512 ,

I apologise for the delay in responding to your question. This is not currently possible as per design. so the short answer is no.

Specific to the use case, I cannot see this as something I would use myself, and that does not mean it cannot / should not be done. I would use a quick short shell alias for commands that I use often as an alternative, in the meantime.

Can you provide some more details on use cases / scenarios where this would be useful? I have tagged this as a question and "need comments", to see what others think.

Thanks!

**Comment by Ilyes512** [comment]
At this point I don’t use tmux anymore. My use case is in the initial post above. I frequently worked on different projects. I wanted to use tmuxp to configure all my workspaces, but I didnt wanted the (little) overhead of running al containers if I wasn’t working on them. So in case I do want to work on a project it would have been nice to switch to it and hit return to start.

**Comment by rfoliva** [comment]
Hi @Ilyes512 ,

Thanks for getting back to me and closing. I hope that you find more reasons to use tmux, and tmuxp (of course!).

I have been thinking about this though, and had an idea that proved to work. Give it a try:

`shell_command: read && docker-compose up`

This will give you the behaviour your are looking for. I tried and it works.

I hope this helps!

Thanks,
Ricardo

**Comment by Ilyes512** [comment]
If I ever decide to come back to tmux I will definitely try this :) thanks for your time!

**Comment by kyluca** [comment]
Had a similar use case and came looking for this, thanks for the tip @rfoliva. Worked as desired for me :+1:

**Comment by kohane27** [comment]
@rfoliva Just dropping another appreciation comment 6 years later that `shell_command: read && docker-compose up` is perfect. Thank you again! Have a great day:)
