### ISSUE TITLE
Command `pipenv shell` and `workon <virtuelenvhere>` commands cause other not to run.

### ISSUE THREAD

**Issue by georgreen** [tmux-python/tmuxp#412]
**Current behavior**
The `pipenv` and `workon` command blocks others from running.

**Expected behavior**
- Run `pipenv` or `workon` to activate virtual env then run the other commands.

#### Relevant tmuxp configuration
<img width="959" alt="screen shot 2018-08-06 at 17 03 49" src="https://user-images.githubusercontent.com/17669596/43721171-c559ace8-999a-11e8-962c-acda5a3386cf.png">

#### Screenshot
For example with this config 
<img width="923" alt="screen shot 2018-08-06 at 17 05 24" src="https://user-images.githubusercontent.com/17669596/43721296-18053db8-999b-11e8-93df-765c9e5071ea.png">

Results:

<img width="885" alt="screen shot 2018-08-06 at 17 06 11" src="https://user-images.githubusercontent.com/17669596/43721336-2bb66d5a-999b-11e8-8b95-a12a30af14ba.png">

 - echo pane 1 run flask server here stuf
 - python manage.py runserver # run python server

- The above commands were not executed

**Comment by tony** [comment]
Yeah I faced similar issues with `pipenv shell`.

Does this work better? ``source `pipenv --venv`/bin/activate``

Example: https://github.com/tmux-python/tmuxp/blob/c6dd4ff/.tmuxp.yaml

**Comment by georgreen** [comment]
@tony Thanks that solves the issues for commands not running but the virtual env is not activated properly using that method. I have also noticed that when I load my pyenv, the startup time increases significantly. 

Screenshot:
- command works before: tmux not loaded
<img width="1628" alt="screen shot 2018-08-07 at 12 00 08" src="https://user-images.githubusercontent.com/17669596/43765829-8cad2d8a-9a39-11e8-8bac-5b2a3d9ae45a.png">

- command fails(does not activate the virtual env properly) after: tmux loaded
<img width="1641" alt="screen shot 2018-08-07 at 11 59 41" src="https://user-images.githubusercontent.com/17669596/43765889-bcbe69d0-9a39-11e8-926f-83bab04bb91c.png">

- pipenv works fine, the intresting thing is that it triggers the same command:

<img width="1626" alt="screen shot 2018-08-07 at 11 58 31" src="https://user-images.githubusercontent.com/17669596/43766147-62cda322-9a3a-11e8-9013-9a469dd66e63.png">

**Comment by istinspring** [comment]
why closed? i got similar problem with tmuxp + virualenvwrapper, somehow `workon someenvironment` caused `ModuleNotFound` but they're installed.

**Comment by tony** [comment]
@istinspring I'll reopen, but not sure how to approach a fix for this.

**Comment by istinspring** [comment]
tmuxp or tmux itself definitely doing something weird with environment.

**Comment by istinspring** [comment]
i think it's related to https://github.com/conda/conda/issues/6826

there is fix: 

```
[[ -z $TMUX ]] || conda deactivate; conda activate base
```

looks like it works for me with tmuxp session loaded (where i activate conda environment)

```
which python
/usr/local/Caskroom/miniconda/base/envs/pcg/bin/python
```

it's tmux related i guess?

**Comment by joseph-flinn** [comment]
@georgreen @oiwn Thanks for using tmuxp! It looks like the consensus for this issue was that it was not with tmuxp? If that's the case I am going to close this issue. Feel free to reopen it if not.

**Comment by italovieira** [comment]
I faced the same problem. The point is that `pipenv shell` creates a new subshell, making it difficult to execute commands inside the venv from scripts. Thus, the next commands will not be executed inside the `pipenv shell`.

**Comment by italovieira** [comment]
For those who want anyway to enter `pipenv shell` and run a command anyway:

```sh
pipenv shell -- python manage.py runserver
```

**Comment by italovieira** [comment]
An example, for those who want anyway to enter `pipenv shell` and run a command anyway:

```sh
pipenv shell -- python manage.py runserver
```

**Comment by italovieira** [comment]
An example in one line, for those who want to enter `pipenv shell` and run a command anyway:

```sh
pipenv shell -- python manage.py runserver
```

**Comment by tony** [comment]
@italovieira personally I've since moved to `poetry`.  

Have you tried `pipenv run ./manage.py runserver`?

**Comment by italovieira** [comment]
@tony I even prefer your suggestion. But, there may be situations where you prefer to run a command and stay inside `pipenv shell`.

**Comment by tony** [comment]
@italovieira yeah

And I assume this approach didn't work either? 
https://github.com/tmux-python/tmuxp/blob/c6dd4ff96b4b45eb8c5067b7cea2b068693a1af6/.tmuxp.yaml#L1-L5

```yaml
shell_command_before: 
  - '[ -d `pipenv --venv` ] && source `pipenv --venv`/bin/activate && reset'
```


What if you did a `sleep 1; pip shell` or `sleep 1; source `pipenv --venv`/bin/activate`?
