### ISSUE TITLE
Setting the current working directory is not persistent

### ISSUE THREAD

**Issue by pgaxatte** [tmux-python/tmuxp#469]
When creating a simple session like this:
```
session_name: test
start_directory: /tmp
windows:
- panes:
  -
```

It creates a window in the right directory but if I open a new window, it falls back on `$HOME`.
I don't have this behaviour with `tmux new -s test -c /tmp`.

tmux version: 2.6
tmuxp version: 1.4.2
libtmux version: 0.8.0
tmuxp and its dependencies were installed via `pip install --user` (python2)

**Comment by koleksiuk** [comment]
I have the same issue. Could anyone take a look at this sometime in the future?

**Comment by danielemegna** [comment]
I'll propose a fix for it this weekend at the next [Open Source Saturday](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/events/267083261/) :point_up:

**Comment by joseph-flinn** [comment]
@pgaxatte @koleksiuk @danielemegna @kierun Thanks all for using tmuxp! This issue has been fixed with PR https://github.com/tmux-python/tmuxp/pull/639.
