### ISSUE TITLE
Components for packaging missing in sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [tmux-python/tmuxp#474]
The tests/fixtures/.sh scripts are missing in the pypi source tarball, making it impossible to run the tests using that tarball. Please add them and check, if there's anything else missing!

**Comment by rfoliva** [comment]
Hi @dvzrv.,

I think I found the issue and should have this fixed soon, after discussing it with @tony on how to best address the issue.


Thanks,
Ricardo

**Comment by rfoliva** [comment]
Hi @dvzrv,

I have just released v.1.5.1 to pypi and created new tag v1.5.1 in the repo.

Can you please try and let me know if you are now able to build it correctly?

Thanks!

**Comment by dvzrv** [comment]
Hey! sorry for the extreme delay. Must have forgotten this issue when upgrading.
The scripts are now there, but the `examples` folder is missing.

**Comment by dvzrv** [comment]
@tony with 1.8.1 *all* tests and examples are now missing in the sdist tarball :-/

```
-rw-r--r-- 0/0            1076 2020-10-31 22:47 tmuxp-1.8.1/LICENSE
-rw-r--r-- 0/0            8436 2021-06-14 20:53 tmuxp-1.8.1/README.rst
-rw-r--r-- 0/0            2073 2021-06-14 23:46 tmuxp-1.8.1/pyproject.toml
-rw-r--r-- 0/0             434 2021-06-14 23:46 tmuxp-1.8.1/tmuxp/__about__.py
-rw-r--r-- 0/0             341 2021-06-14 20:53 tmuxp-1.8.1/tmuxp/__init__.py
-rw-r--r-- 0/0             562 2021-06-14 20:53 tmuxp-1.8.1/tmuxp/_compat.py
-rw-r--r-- 0/0           39708 2021-06-14 20:53 tmuxp-1.8.1/tmuxp/cli.py
-rw-r--r-- 0/0           16717 2021-06-14 20:53 tmuxp-1.8.1/tmuxp/config.py
-rw-r--r-- 0/0            1347 2021-06-14 20:53 tmuxp-1.8.1/tmuxp/exc.py
-rw-r--r-- 0/0            3937 2021-06-14 20:53 tmuxp-1.8.1/tmuxp/log.py
-rw-r--r-- 0/0            7241 2021-01-10 23:50 tmuxp-1.8.1/tmuxp/plugin.py
-rw-r--r-- 0/0            6874 2021-06-14 20:53 tmuxp-1.8.1/tmuxp/shell.py
-rw-r--r-- 0/0            4224 2021-06-14 20:53 tmuxp-1.8.1/tmuxp/util.py
-rw-r--r-- 0/0           14331 2021-06-14 20:53 tmuxp-1.8.1/tmuxp/workspacebuilder.py
-rw-r--r-- 0/0            9517 2021-06-14 23:47 tmuxp-1.8.1/setup.py
-rw-r--r-- 0/0            9903 2021-06-14 23:47 tmuxp-1.8.1/PKG-INFO
```

Without using the tarball from github I can neither run the tests nor install examples.

**Comment by tony** [comment]
@dvzrv  Uh oh!  I think I know what happened.  Looking.

**Comment by tony** [comment]
@dvzrv If you try 1.8.2, any better?

**Comment by dvzrv** [comment]
@tony many thanks! That works perfectly now! :)
