### ISSUE TITLE
tmuxp freeze without providing a SESSION_NAME fails

### ISSUE THREAD

**Issue by sakalys** [tmux-python/tmuxp#485]
When issuing a `tmuxp freeze [OPTIONS] SESSION_NAME` by omitting the "SESSION_NAME" we get an error saying _Error: Missing argument "SESSION_NAME"_. Though the help text says the following:
> If SESSION_NAME is provided, snapshot that session. Otherwise, use the
  current session.

I expect it to freeze the current session when issuing just `tmuxp freeze` (without additional arguments).

---
tmuxp 1.5.1

**Comment by joseph-flinn** [comment]
@sakalys Thanks for using tmuxp! It looks like the this issue has been fixed. Please feel free to reopen this issue if your problem was not fixed with PR https://github.com/tmux-python/tmuxp/pull/491
