### ISSUE TITLE
pane names?

### ISSUE THREAD

**Issue by jby** [tmux-python/tmuxp#521]
How do I set window/pane names properly?

This
```
    - window-name: remote-host
      panes:
        - ssh remote-host
```
gives me a window called "ssh", which is completely useless if I have more than one - AND it kind of makes using tmuxp moot, since I have to to through all my windows and reset their names after starting my session...

Besides #86 _REALLY_ need to be fixed as well.

As of now I have this in my .tmux.conf:
`bind-key S command-prompt -p ssh "new-window -n %1 'ssh %1'"`
which make me able to use 'send-prefix S' to create a new window with a remote session to that remote host, AND the _name_ of that remote host, without a spawned shell to start with. When I logout from the host, the window dies.
I was really hoping that could be re-created with tmuxp.

**Comment by ssh352** [comment]
it would be nice to have pane names.

**Comment by lukruh** [comment]
+1 for rename panes feature.. it's a pain to do it by hand over and over again

**Comment by aRkedos** [comment]
+1 would be nice, bit I think it would also be a pain to implement because pane names are using printf-escape sequences :/

**Comment by joseph-flinn** [comment]
Thanks for using tmuxp! Looks like there is an issue (https://github.com/tmux-python/tmuxp/issues/384) created for this already. This request is on the top of the list of things to develop and hopefully will be coming soon.
