### ISSUE TITLE
Pass flags to newly created session?

### ISSUE THREAD

**Issue by deliciouslytyped** [tmux-python/tmuxp#532]
Can tmuxp pass flags to a new session? (IIRC tmuxinator has something like that)
If not it probably needs to be handled somewhere around where session_name" is handled.

**Comment by deliciouslytyped** [comment]
Ok I actually wanted to try passing `-x` and `-y` but it looks like libtmux `new_session` already does that with specific large values if the tmux version supports the arguments, so what I specifically wanted to do seems to be covered.

**Comment by deliciouslytyped** [comment]
Ok, I think this is covered by the `options` setting? I just didn't notice it in the documentation.
It would be nice to have an explicit list of options separate from the mass of examples (which is indeed good to have though).

**Comment by joseph-flinn** [comment]
@deliciouslytyped Thanks for using tmuxp! If I am not mistaken, the `global_options` and `options` get passed through to the tmux server. all of these options are documented in the tmux man page. tmuxp supports many versions of tmux, and keeping documentation on all of the different options of all of the versions of tmux we support seems like a daunting task. Thanks again for your contribution to the community!

**Comment by deliciouslytyped** [comment]
Hey, thanks for the reply.

I don't remember very well what exactly was going on here, but the bottom line is, how does a user figure out what the supported options are and how to pass them? If there is some simple rule for translating the yaml to the tmux options, cool.  Alternatively, If it's hard to figure out what's supported by what version, that kind of seems like a code smell. Also it sounds like in the ideal case, documentation for this should be generated as opposed to hand-written, perhaps enumeration in some sort of feature matrix. This is probably good for developers too?

At this point I'm more comfortable with "read the source, Luke" than I used to be, so in my case that probably suffices.

**Comment by joseph-flinn** [comment]
I believe all of the options (global_options, session_options, and window_options) are passed down from `tmuxp` to `libtmux` and `libtmux` runs them directly in `tmux` as a command (\<prefix\> + : + \<cmd\>). So all global, session, and window options in the `tmux` man page are valid here and pretty well documented ([man tmux](https://man7.org/linux/man-pages/man1/tmux.1.html) => sub heading "OPTIONS"). 

After a quick search, I couldn't find any versioned man pages for tmux, so I think the simplest solution is to point the user to their local tmux man page. Do you see and edge case that this wouldn't cover?

**Comment by deliciouslytyped** [comment]
I'm no professional documentation writer, but if it's just some sort of passthrough, yeah it sounds fine to just redirect to the tmux documentation. After all, that's where the semantics are implemented. Say what you mean.

Tmuxp/libtmux's job would then be to clearly specify how the translation works.
