### ISSUE TITLE
New "freeze" behaviour – allow overwriting

### ISSUE THREAD

**Issue by sakalys** [tmux-python/tmuxp#537]
Currently, if you attempt to freeze and save the config to an existing file, then you are informed that you cannot do so, because the file already exists. I am willing to code and submit a pull request that would allow the `tmuxp freeze` command to overwrite the specified file. 

Does anyone see any problems with this, because I did not look anywhere else in the code except the function responsible for the command?

The following is a linked issue, but it got closed because of staling – https://github.com/tmux-python/tmuxp/issues/64.

**Comment by joseph-flinn** [comment]
@sakalys Thanks for using tmuxp! It looks like this issue has been solved with the `tmuxp freeze --force <session_name>`. I'm going to go ahead and close this issue. Please feel free to reopen it if that change didn't add the functionality you were after.
