### ISSUE TITLE
tmuxp command not found

### ISSUE THREAD

**Issue by Tycholiz** [tmux-python/tmuxp#584]
### summary
I have tried to install with `pip install --user tmuxp`. On subsequent executions of that command, I get this, indicating the install went through without a hiccup:

```
Requirement already satisfied: tmuxp in ./Library/Python/3.7/lib/python/site-packages (1.5.4)
Requirement already satisfied: click>=7<8 in ./Library/Python/3.7/lib/python/site-packages (from tmuxp) (7.1.2)
Requirement already satisfied: kaptan>=0.5.10 in ./Library/Python/3.7/lib/python/site-packages (from tmuxp) (0.5.12)
Requirement already satisfied: libtmux>=0.8<0.9 in ./Library/Python/3.7/lib/python/site-packages (from tmuxp) (0.8.2)
Requirement already satisfied: colorama>=0.3.9 in ./Library/Python/3.7/lib/python/site-packages (from tmuxp) (0.4.3)
Requirement already satisfied: PyYAML<6,>=3.13 in ./Library/Python/3.7/lib/python/site-packages (from kaptan>=0.5.10->tmuxp) (5.3.1)
```

However, when I run `tmuxp`, I get `Command not found`.

### Step 2: Provide tmuxp details
  * Python version: 3.7.7
  * Python2 version: 2.7.16
  * system PATH: `/usr/local/opt/python/libexec/bin:/usr/local/sbin:/Users/kyletycholiz/Scripts/backup:/Users/kyletycholiz/Scripts:/Users/kyletycholiz/bin:/usr/local/bin:/usr/bin/python2:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/node_modules/.bin:/Applications/Cerebro.app/Contents/Frameworks/Cerebro:/Users/kyletycholiz/.local/bin:/Users/kyletycholiz/.fzf/bin`
  * tmux version: 3.1b
  * tmuxp version: **not found**
  * tmux path: /usr/local/bin/tmux
  * tmuxp path: **not found**
  * libtmux version: **not found**
  * shell: zsh

### Step 3: Describe your environment
  * Architecture: OSX
  * OS version: Catalina 10.15.4

### Additional info
- I have used homebrew to install python. I have read somewhere in my research of this problem that homebrew and pip do not play nicely. There was a fix in that thread that seems to have fixed the pip issue (tmuxp was complaining about the pip version). That thread is [here](https://github.com/pypa/pip/issues/6399)
- It appears that both python2 and python3 are executable based on my PATH variable
- I have gone through [this similar thread](https://github.com/tmux-python/tmuxp/issues/331), but the discussion did not lead to an answer.

**Comment by Tycholiz** [comment]
anybody have any insight to what's going on? It seems that python is not being found correctly, but I have no idea why, seeing as both python2 and python3 are in my PATH, and I'm not getting any error message that might indicate that it needs a different sub-version of python

**Comment by ivankatliarchuk** [comment]
The tmux installed in `/Library/Python/3.7/lib/python/site-package` which probably means the `tmuxp` script is installed into the `~/Library/Python/3.7/bin` and this is not in PATH. 
The possible solution is `PATH=$(python3 -m site --user-base)/bin:$(python -m site --user-base)/bin:$PATH`

**Comment by Tycholiz** [comment]
this worked, thank you very much!
