### ISSUE TITLE
"tmuxp freeze" questions "save to" and "save to" are unclear

### ISSUE THREAD

**Issue by NGenetzky** [tmux-python/tmuxp#627]
I want to start by saying thank you for creating such an awesome library and program. I enjoyed using it - although I do wish I used it more.

### Step 1: Provide a summary of your problem

>  * For general technical questions, problems or feature requests related to the code **in this repository** file an issue.

Reword one of the questions in `tmuxp freeze`.

### Step 2: Provide tmuxp details

NOTE: I really wish you would give a command line (such as the one below) that people could simply copy and paste to provide the info you want.

```bash
└─>( set -x ; echo $PATH ; tmux --version ; tmuxp --version ; which tmux ; dpkg --list | grep tmux ; echo $SHELL)  
+-zsh:17> echo /home/ngenetzky/appimages/:/home/ngenetzky/.local/bin:/home/ngenetzky/bin:/home/ngenetzky/appimages/:/home/ngenetzky/.local/bin:/home/ngenetzky/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
/home/ngenetzky/appimages/:/home/ngenetzky/.local/bin:/home/ngenetzky/bin:/home/ngenetzky/appimages/:/home/ngenetzky/.local/bin:/home/ngenetzky/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+-zsh:17> tmux --version
usage: tmux [-2CluvV] [-c shell-command] [-f file] [-L socket-name]
            [-S socket-path] [command [flags]]
+-zsh:17> tmuxp --version
tmuxp 1.5.4
+-zsh:17> which tmux
/usr/bin/tmux
+-zsh:17> dpkg --list
+-zsh:17> grep '--color=auto' '--exclude-dir=.bzr' '--exclude-dir=CVS' '--exclude-dir=.git' '--exclude-dir=.hg' '--exclude-dir=.svn' '--exclude-dir=.idea' '--exclude-dir=.tox' tmux
ii  python3-libtmux                               0.8.2-2                               all          Python scripting library and ORM for tmux (python3)
ii  python3-tmuxp                                 1.5.4-1                               all          tmux session manager (Python 3)
ii  tmux                                          3.0a-2ubuntu0.1                       amd64        terminal multiplexer
ii  tmuxp                                         1.5.4-1                               all          tmux session manager
+-zsh:17> echo /bin/zsh
/bin/zsh
```

Skipped these:
>  * output of `tmux list-sessions`, `tmux list-windows`, `tmux list-panes`
>  * output of `tmux show-options -g`, `tmux show-window-options -g`
>  * output of `tmuxp freeze <SESSION_NAME>`

### Step 3: Describe your environment

```
└─>uname -a
Linux ngenetzky-novo 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

#### Steps to reproduce:

  1. start the session
  2. freeze
  3. observe prompts

#### Observed Results:

>  * What happened?  This could be a description, log output, etc.

```
└─>tmuxp freeze sys
Convert to [yaml]: 
session_name: sys
windows:
- focus: 'true'
  layout: c49d,208x55,0,0,0
  options: {}
  panes:
  - focus: 'true'
    shell_command: python3
  start_directory: /home/ngenetzky/workspace/ngenetzky-sysadmin
  window_name: zsh

---------------------------------------------------------------
Freeze does it best to snapshot live tmux sessions.

The new config *WILL* require adjusting afterwards. Save config? [y/N]: y
Save to: /home/ngenetzky/.tmuxp/sys.yaml [/home/ngenetzky/.tmuxp/sys.yaml]: 
Save to /home/ngenetzky/.tmuxp/sys.yaml? [y/N]: y
Saved to /home/ngenetzky/.tmuxp/sys.yaml.
```

#### Expected Results:

> * What did you expect to happen?

Reword this line (`Save to: /home/ngenetzky/.tmuxp/sys.yaml [/home/ngenetzky/.tmuxp/sys.yaml]: `) so that it more clearly indicates you are naming the file - rather than literally having it be the same question as the next line (`Save to /home/ngenetzky/.tmuxp/sys.yaml? [y/N]: y`)

#### Relevant Code:

NA

**Comment by aRkedos** [comment]
I would even argue that this line is maybe not really necessary because the user already needs to give a name for the `freeze` command which can be used as the filename and by default all configs are saved to $HOME/.tmuxp.

On the other hand completely removing this would take away control where to put those config files (would be fine in my book).

**Comment by joseph-flinn** [comment]
@NGenetzky Thanks for using `tmuxp` and thank you for your suggestion in Step 2! We definitely agree and in the `1.7.0` release have included a `tmuxp debug-info` command to help collect the needed debugging information.
