### ISSUE TITLE
 RuntimeError("Unable to determine handler") for folders with . (dot)

### ISSUE THREAD

**Issue by oiwn** [tmux-python/tmuxp#630]
### Step 1: Provide a summary of your problem
  
Keep getting  RuntimeError("Unable to determine handler") if parent folder contain . (dot)
If rename folder and remove dot the problem disappearing.

### Step 2: Provide tmuxp details
  * Python 3.8.3
  * tmux 3.1b
  * tmuxp 1.5.6
  * zsh

### Step 3: Describe your environment
  * Architecture: Darwin
  * OS version: 10.15.7 (19H2)

### Step 4: Describe the problem:

Looks like folder shouldn't contain dot.

#### Steps to reproduce:

  1. mkdir folderwith.dot
  2. cd folderwith.dot && copy ../.tmuxp.yaml .
  3. tmuxp load .

#### Observed Results:
```
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/tmuxp/cli.py", line 834, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/tmuxp/cli.py", line 501, in load_workspace
    sconfig = sconfig.import_config(config_file).get()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/kaptan/__init__.py", line 87, in import_config
    raise RuntimeError("Unable to determine handler")
```

#### Expected Results:
 Load tmuxp configuration stored in `.tmuxp.yaml`

**Comment by tony** [comment]
@oiwn This should be fixed as of 1.5.7

Better now? 

https://tmuxp.git-pull.com/history.html#tmuxp-1-5-7-2020-10-31

**Comment by oiwn** [comment]
@tony cool! Thank you!

**Comment by joseph-flinn** [comment]
@oiwn Seems like the issue has been fixed. Closing this issue. Feel free to reopen if it continues to be a problem
