### ISSUE TITLE
The start_directory directive is not respected when creating new panes.

### ISSUE THREAD

**Issue by ygworldr** [tmux-python/tmuxp#631]
### Step 1: Provide a summary of your problem

The `start_directory` directive is not respected when creating new panes.

### Step 2: Provide tmuxp details

  * Python version 3.9.0
  * system PATH NA
  * tmux version 3.1
  * tmuxp version 1.5.5
  * tmux path ~/bin/tmux
  * tmuxp path, ~/.pyenv/shims/tmuxp
  * libtmux version 0.8.3
  * shell zsh 5.8
  * output of `tmux list-sessions`, `tmux list-windows`, `tmux list-panes` NA
  * output of `tmux show-options -g`, `tmux show-window-options -g` NA
  * output of `tmuxp freeze <SESSION_NAME>` NA

### Step 3: Describe your environment
  * Architecture: x86_64 GNU/Linux
  * OS version: Fedora 32

#### Steps to reproduce:

1. Create a simple configuration setting `start_directory` to `~/ook` & save as `~/.tmuxp/ook.yaml`.
2. Load it via `tmuxp load ook`
3. Create a new windows: `ctrl+a + c`
4. I was expected the new pane current directory to be `~/ook`
5. The new pane is opened in `~/`.

#### Observed Results:
 
The new pane is opened in `~/`.

#### Expected Results:

I was expected the new pane current directory to be `~/ook`

#### Relevant Code:

```session_name: App Server
start_directory: ~/ook
windows:
- window_name: top
  panes:
    - shell_command:
        - pwd
```

**Comment by joseph-flinn** [comment]
@ygworldr Thanks for raising this issue. It seems like the main `start_directory` is not setting the current working directory of `tmux` as the `tmux -c ./ook` would do. I have yet to identify whether this is an issue in `tmuxp` or the underlying `libtmux`. I'll look into it and report back here.

**Comment by ygworldr** [comment]
I am happy to test any fix, if you wanted me to.

**Comment by joseph-flinn** [comment]
Ok, great! I'll let you know when I have a fix

**Comment by joseph-flinn** [comment]
@ygworldr I am pretty sure that PR #639 fixes this issue. It is currently in PR. Feel free to test it out.

**Comment by ygworldr** [comment]
Upgraded and the bug is indeed fixed. Thank you so much.
