### ISSUE TITLE
1.7.0: running pytest only possible with poetry or using PYTHONPATH

### ISSUE THREAD

**Issue by dvzrv** [tmux-python/tmuxp#658]
### Step 1: Provide a summary of your problem
When trying to package 1.7.0 for Arch Linux I ran pytest against the build. Unfortunately the current setup with poetry makes this fairly hard, as [the test plugins are included in the pyproject.toml](https://github.com/tmux-python/tmuxp/blob/868fe19a7c7fefa31f0fcd27154021334778431f/pyproject.toml#L72-L77), of which pytest is unaware.

This can only be circumvented by adding the fairly long paths of all plugins to `PYTHONPATH` before calling pytest:

```
  PYTHONPATH="build:tests/fixtures/pluginsystem/plugins/tmuxp_test_plugin_awf" \
  PYTHONPATH+=':tests/fixtures/pluginsystem/plugins/tmuxp_test_plugin_bs' \
  PYTHONPATH+=':tests/fixtures/pluginsystem/plugins/tmuxp_test_plugin_bwb' \
  PYTHONPATH+=':tests/fixtures/pluginsystem/plugins/tmuxp_test_plugin_fail' \
  PYTHONPATH+=':tests/fixtures/pluginsystem/plugins/tmuxp_test_plugin_owc' \
  PYTHONPATH+=":tests/fixtures/pluginsystem/plugins/tmuxp_test_plugin_r:$PYTHONPATH"
  export PYTHONPATH
```
The above is cumbersome and error-prone, as new plugins are potentially added to the test scenario.

### Step 2: Provide tmuxp details

```
$ pytest -v -k "not test_pane_order"

============================= test session starts ==============================
platform linux -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /build/tmuxp/src/tmuxp-1.7.0, configfile: setup.cfg
plugins: rerunfailures-9.1.1
collecting ... collected 78 items / 1 error / 1 deselected / 76 selected

==================================== ERRORS ====================================
______________________ ERROR collecting tests/test_cli.py ______________________
ImportError while importing test module '/build/tmuxp/src/tmuxp-1.7.0/tests/test_cli.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_cli.py:18: in <module>
    from tmuxp_test_plugin_bwb.plugin import PluginBeforeWorkspaceBuilder
E   ModuleNotFoundError: No module named 'tmuxp_test_plugin_bwb'
=========================== short test summary info ============================
ERROR tests/test_cli.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
======================== 1 deselected, 1 error in 0.32s ========================
```

  * Include output of `tmuxp debug-info`
  * Include any other pertinant system info not captured

#### Steps to reproduce:
  1. python setup.py build
  2. pytest -v

#### Observed Results:
The pytest call is unaware of the test plugins and fails.

#### Expected Results:
After build pytest can be run in a normal environment.

#### Relevant Code:
 n/a

**Comment by joseph-flinn** [comment]
@dvzrv According to issue https://github.com/tmux-python/tmuxp/issues/625, we are looking to migrate fully to poetry for building and publishing. Is it possible to use poetry to package fro Arch? I believe that question is still open on https://github.com/tmux-python/tmuxp/issues/625. If it not, would you mind dropping a quick note here and mention that issue so that it will link the two?

**Comment by tony** [comment]
I may be able to reconfigure the tests to add the packages to paths this weekend.

**Comment by tony** [comment]
@dvzrv [1.7.2](https://pypi.org/project/tmuxp/1.7.2/) any better?

**Comment by dvzrv** [comment]
@tony many thanks! 1.7.2 works again without exporting PYTHONPATH for those resources! :)

**Comment by tony** [comment]
@dvzrv Good to know this is working now.  Big thanks still goes to @joseph-flinn for creating the plugin system!
