### ISSUE TITLE
Setting window_name: '' doesn't work

### ISSUE THREAD

**Issue by trankchung** [tmux-python/tmuxp#822]
### Step 1: Provide a summary of your problem
Setting `window_name: ''` doesn't make the window name empty.

### Step 2: Provide tmuxp details

- Include output of `tmuxp debug-info`
```
environment:
	dist: macOS-12.6-arm64-arm-64bit
	arch: arm64
	uname: Darwin; ctran0322mac; 21.6.0
	version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101
-------------------------
python version: 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)]
system PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
tmux version: 3.3
libtmux version: 0.15.1
tmuxp version: 1.15.0
tmux path: /opt/homebrew/bin/tmux
tmuxp path: /opt/homebrew/Cellar/tmuxp/1.15.0/libexec/lib/python3.10/site-packages/tmuxp
shell: /bin/zsh
```
### Step 3: Describe the problem:
Setting `window_name: ''` should make the window name empty. I know this can be done by removing `#W` from tmux but this should be supported. I have 9 windows that I use by indices only. I don't need the name of the window.
#### Observed Results:

- What happened? This could be a description, log output, etc.
The window name automatically taken from the last command executed.

#### Expected Results:

- What did you expect to happen?
The window name should be empty.

**Comment by tony** [comment]
Good catch

I think this makes sense to do a PR for.

**Comment by trankchung** [comment]
@tony Here's the PR into libtmux that fixes this.

https://github.com/tmux-python/libtmux/pull/444

**Comment by tony** [comment]
@trankchung thank you! 

Is that test thing I asked for [here](https://github.com/tmux-python/libtmux/pull/444/files#r979497736) okay?

P.S. can you sign the [CLA](https://github.com/tmux-python/libtmux/pull/444#issuecomment-1257355249)?

P.P.S Like the profile icon of Tux!

**Comment by tony** [comment]
@trankchung If you try tmuxp, [v1.16.1](https://pypi.org/project/tmuxp/1.16.1/), is anything different?
